services:
  project:
    restart: always
    container_name: ug-project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
      - '3000:3000'
    volumes:
      - type: bind
        source: ./
        target: /Users/sagnik/Work and Research/Math/Projects/ug-dissertation
    command: sh -c "fastapi dev --host 0.0.0.0 backend/server.py && python3 -m http.server 3000"
    